name: therapia_flutter_application
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.3


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  salomon_bottom_bar: ^3.0.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/core/assets/icon/therpeia_logo.ico"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/core/assets/images/therpeia_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/core/assets/images/therpeia_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/core/assets/images/therpeia_logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it:
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.15
  # gestion de la navigation  API 2.0(Declarative) 1.0(impérative)
  #Navigator.push(...)xxxx déconseillé 1.0
  go_router: ^6.0.0
  validators:

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#F9F9F9"
  image: "lib/core/assets/images/therpeia_logo.png"
  android: true
  ios: true
  

flutter:

  
  uses-material-design: true

  assets: 
    - lib/core/assets/images/
    - lib/core/assets/icon/

  fonts:
    - family: Quicksand
      fonts:
          - asset: lib/core/assets/fonts/Quicksand-Bold.ttf
          - asset: lib/core/assets/fonts/Quicksand-Light.ttf
          - asset: lib/core/assets/fonts/Quicksand-Medium.ttf
          - asset: lib/core/assets/fonts/Quicksand-Regular.ttf
          - asset: lib/core/assets/fonts/Quicksand-SemiBold.ttf
